feat: remove legacy configuration files and add new dotbot setup

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,38 +1,96 @@
 #!/usr/bin/env bash
 
-set -e
+DOTFILES="$(pwd)"
+COLOR_GRAY="\033[1;38;5;243m"
+COLOR_BLUE="\033[1;34m"
+COLOR_GREEN="\033[1;32m"
+COLOR_RED="\033[1;31m"
+COLOR_PURPLE="\033[1;35m"
+COLOR_YELLOW="\033[1;33m"
+COLOR_NONE="\033[0m"
 
-# Exporting the specific shell we want to work with:
-
-SHELL='/bin/bash'
-export SHELL
-
-# Standard dotbot pre-configuration:
-
-readonly DOTBOT_DIR='dotbot'
-readonly DOTBOT_BIN='bin/dotbot'
-readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-
-readonly ARGS="$@"
-
-cd "$BASEDIR"
-git submodule sync --quiet --recursive
-git submodule update --init --recursive
-
-# Linking dotfiles:
-
-run_dotbot () {
-  local config
-  config="$1"
-
-  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
-    -d "$BASEDIR" \
-    --plugin-dir dotbot-brewfile \
-    -c "$config" $ARGS
+title() {
+    echo -e "\n${COLOR_PURPLE}$1${COLOR_NONE}"
+    echo -e "${COLOR_GRAY}==============================${COLOR_NONE}\n"
 }
 
-run_dotbot '.steps/terminal.yml' || true
-run_dotbot '.steps/dependencies.yml' || true
+error() {
+    echo -e "${COLOR_RED}Error: ${COLOR_NONE}$1"
+    exit 1
+}
 
-bash "./mac/configure-dock.sh"
-bash "./mac/configure-mac.sh"
+warning() {
+    echo -e "${COLOR_YELLOW}Warning: ${COLOR_NONE}$1"
+}
+
+info() {
+    echo -e "${COLOR_BLUE}Info: ${COLOR_NONE}$1"
+}
+
+success() {
+    echo -e "${COLOR_GREEN}$1${COLOR_NONE}"
+}
+
+get_linkables() {
+    find -H "$DOTFILES" -maxdepth 3 -name '*.symlink'
+}
+
+setup_symlinks() {
+    title "Creating symlinks"
+
+    ./run-dotbot
+}
+
+setup_homebrew() {
+    title "Setting up Homebrew"
+
+    if test ! "$(command -v brew)"; then
+        info "Homebrew not installed. Installing."
+        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    fi
+
+    brew bundle
+}
+
+function setup_shell() {
+    title "Configuring shell"
+
+    zsh_path="$(which zsh)"
+    if ! grep "$zsh_path" /etc/shells; then
+        info "adding $zsh_path to /etc/shells"
+        echo "$zsh_path" | sudo tee -a /etc/shells
+    fi
+
+    if [[ "$SHELL" != "$zsh_path" ]]; then
+        chsh -s "$zsh_path"
+        info "default shell changed to $zsh_path"
+    fi
+
+    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
+}
+
+setup_macos() {
+    title "Configuring macOS"
+    if [[ "$(uname)" == "Darwin" ]]; then
+
+        echo "show hidden files by default"
+        defaults write com.apple.Finder AppleShowAllFiles -bool true
+
+        echo "only use UTF-8 in Terminal.app"
+        defaults write com.apple.terminal StringEncodings -array 4
+
+        echo "Kill affected applications"
+
+        for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1; done
+    else
+        warning "macOS not detected. Skipping."
+    fi
+}
+
+setup_symlinks
+setup_homebrew
+setup_shell
+setup_macos
+
+echo -e
+success "Done."
